### ISSUE TITLE
L3_EX: Build exercises in R for advanced reporting class 2

### ISSUE THREAD

**Issue by ex-man** [ex-man/GeneralInsurance_Class#15]
There need to be R exercises supporting lesson 2 concept

**Comment by cvoky** [comment]
Ideas:
- [ ] frequency tables
- [ ] outlier analysis
- [ ] shape analysis

**Comment by ex-man** [comment]
TO BE DONE BY @cvoky 
0. import @ambasador77  data,
1. ProRate factor => earned exposure
2. Join claims and policy exposure
3. decision tree analysis to find who is driving the problem (in losses).
4. Then apply the decision tree to discounted losses (same as above)
5. We can add variation in finding who is driving number of claims (same as above, different variable)
