### ISSUE TITLE
Lesson2_EX: Build exercises for basic reporting

### ISSUE THREAD

**Issue by ex-man** [ex-man/GeneralInsurance_Class#18]
They need to practice business logic - search for issues with UWR or other KPIs from the lesson

**Comment by cvoky** [comment]
Ideas:

- Add more dimensions in shiny, default is only one
- Use shiny only when necessary, prepare exercices in basic ggplot firstly (bar chart, line chart, ...)

**Comment by cvoky** [comment]
Done at f8f14f4983c198c14f412c0e1da2b679f1c62dae
