### ISSUE TITLE
Clean up the directory

### ISSUE THREAD

**Issue by ex-man** [ex-man/GeneralInsurance_Class#25]
We need to have a clear structure of the directory, so that it is easy to follow. There should be a separate folder for the master shiny app with little code snipers in each lesson

**Comment by cvoky** [comment]
Let's discuss this tomo.

How to arrange?
- shiny (default requirement/coding standard root folder)
- packrat (default requirements root folder)
- data (one folder for data)
- lessons

  - vs. user-friendly view

We need to find balance between clear structure, which is easy to follow and coding standards/requirements.

Ideas?
- simple standalone gadgets/shiny modules per lesson
- tricking the mega-shiny structure
- ...

**Comment by ex-man** [comment]
@cvoky , you own it...
