### ISSUE TITLE
KPIs in Shiny dashboard (for class 2)

### ISSUE THREAD

**Issue by ex-man** [ex-man/GeneralInsurance_Class#7]
It makes sense that we have an interactive dashboard to review the KPIs at the beginning. Students should learn a bit about creating it and we should have everything set up in a way, that they are able to find issues in data via dashboard.

**Comment by cvoky** [comment]
Added simple explanation of shiny framework:
[shiny_prezi_zna.pptx](https://github.com/ex-man/GeneralInsurance_Class/files/1506224/shiny_prezi_zna.pptx)

**Comment by cvoky** [comment]
Leaving foto with a few KPIs from meeting.
![20171127_160810](https://user-images.githubusercontent.com/26393861/33307141-c34a7e28-d415-11e7-8c78-489036c5c19b.jpg)

**Comment by ex-man** [comment]
In terms of expenses, we should not go with fixed and variable split. Just have one variable expense ratio proportional to premium.

**Comment by ex-man** [comment]
By the way: let's make it simple. No plan or other benchmark is needed from now. The benchmark is 0 underwriting result, that is equal to 100% combined ratio.

**Comment by ex-man** [comment]
The critical piece is to link this with the next set of lessons. Relates to #21

**Comment by MatejBreja** [comment]
In Lesson 2 tab we want 4 ways of view (left navigation bar):

1.  Overall
- table with one row labeled as "Total" with LR %, ER %, UWR ($m)
- bar chart left to right next to each row with LR % and ER % staged
- bar chart left to right with UWR ($m)
2. One Dimension Split
- table split by one selected dimension (selector at the top of the page)
3. Multi Dimension Split
- table split by all dimensions (selector for each dimension at the top of the page with possibility to 
      select all)
- table shows all relevant combinations according to filter each on separate row
- bar chart left to right next to each row with LR % and ER % staged
- bar chart left to right with UWR ($m)
4. Trend
- table split by time dimension (selector for each dimension at the top of the page with possibility to 
      select all)
- table shows aggregated view according to filter each time period on separate column
- line chart left to right with time as X-axis showing LR % and CoR%

We need to think about how much we create and how much they need to do.

**Comment by MatejBreja** [comment]
Maybe we should have it all solved in separate branch but provide with basic skeleton and hints in main branch. Similar to VBA training

**Comment by ex-man** [comment]
Think about why you want them to do this. Let’s be careful not to turn this into programming class. It should be about insurance in the first place...

**Comment by cvoky** [comment]
This is status where we are with this issue (mostly for me).

In Lesson 2 tab we want 4 ways of view (left navigation bar):

1. Overall
- [x] table with one row labeled as "Total" with LR %, ER %, UWR ($m) b5bf95576bbe1b1924825bff066fb978780404a6
- [x] bar chart left to right next to each row with LR % and ER % staged b5bf95576bbe1b1924825bff066fb978780404a6
- [x] bar chart left to right with UWR ($m) bc4b5035bac7d155a0831172f971b5721ba20f76
- [x] add premium field to table bc4b5035bac7d155a0831172f971b5721ba20f76
2. One Dimension Split
- [x] table split by one selected dimension (selector at the top of the page) b5bf95576bbe1b1924825bff066fb978780404a6
- [x] bar chart left to right next to each row with LR % and ER % staged b5bf95576bbe1b1924825bff066fb978780404a6
- [x] bar chart left to right with UWR ($m) bc4b5035bac7d155a0831172f971b5721ba20f76
- [x] add premium field to table bc4b5035bac7d155a0831172f971b5721ba20f76
3. Multi Dimension Split
- [x] table split by all dimensions (selector for each dimension at the top of the page with possibility to
select all) 5e0a0b84cd1e2d2423193093679eb5b4501f0d58
- [x] table shows all relevant combinations according to filter each on separate row  5e0a0b84cd1e2d2423193093679eb5b4501f0d58
- [x] add selector for dimension to show on the charts 5e0a0b84cd1e2d2423193093679eb5b4501f0d58
- [x] bar chart left to right next to each row with LR % and ER % staged 5e0a0b84cd1e2d2423193093679eb5b4501f0d58
- [x] bar chart left to right with UWR ($m) 5e0a0b84cd1e2d2423193093679eb5b4501f0d58
4. Trend
- [x] table split by time dimension (selector for each dimension at the top of the page with possibility to
select all) 30135f1e25e085a30407b026902e44b2251028bb
- [x] table shows aggregated view according to filter each time period on separate column
line chart left to right with time as X-axis showing LR % and CoR% 30135f1e25e085a30407b026902e44b2251028bb

**Comment by cvoky** [comment]
@ex-man or @MatejBreja can you review? If so, I will create blank parts where missing code will be as exercise for students.

**Comment by cvoky** [comment]
- [x] tab Focus Group - fix filtering on charts, not working currently 4628868d90e0615c6888d278a9cf50f6ef2cc2c9
- [ ] tab Time Dimension - change type of the graph to line/area, add CoR, rotate 6b84c8d26cd4d4be0c1f2b2ef57936e66204397c

**Comment by ex-man** [comment]
@cvoky, data is here: https://github.com/ex-man/GeneralInsurance_Class/files/1579591/KPIForUniversity_v1.zip

This includes 4 dimensions + time dimension. Let's start with this and we can improve later.

**Comment by ex-man** [comment]
We had a good session with both @cvoky and @ambasador77 and I have changed the way it was designed slightly. The main reason was that the current content was not helping enough to explore the entire issue. The idea should be:
- [x] learn how to convert financial amounts into a reasonable comparisons using KPIs.
- [x] learn how to make small adjustments to Shiny, but copy pasting the existing code a building the same thing with a different dimensions (example shows lossess and expenses, but the new view shows loss and expense ratios)
- [x] once the above is built the investigation happens again.

**Comment by cvoky** [comment]
Done at f8f14f4983c198c14f412c0e1da2b679f1c62dae
